In [5]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def load_confusion_matrix(csv_path):
    """Load confusion matrix from a CSV file."""
    return pd.read_csv(csv_path, header=None).values

def calculate_metrics(conf_matrix):
    """Calculate accuracy, precision, recall, and F1 score from a confusion matrix."""
    # Extract true labels and predictions
    true_labels = []
    predicted_labels = []
    for i in range(conf_matrix.shape[0]):
        for j in range(conf_matrix.shape[1]):
            true_labels.extend([i] * conf_matrix[i, j])
            predicted_labels.extend([j] * conf_matrix[i, j])

    # Calculate metrics
    accuracy = accuracy_score(true_labels, predicted_labels)
    precision = precision_score(true_labels, predicted_labels, average='weighted')
    recall = recall_score(true_labels, predicted_labels, average='weighted')
    f1 = f1_score(true_labels, predicted_labels, average='weighted')

    return accuracy, precision, recall, f1


# Path to the CSV file containing the confusion matrix
csv_path = 'confusion_matrix_results.csv'

# Load the confusion matrix
conf_matrix = load_confusion_matrix(csv_path)

# Calculate the metrics
accuracy, precision, recall, f1 = calculate_metrics(conf_matrix)

# Print the results
print("Confusion Matrix:")
print(conf_matrix)
print("\nMetrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")




Confusion Matrix:
[[49  0  6  0  0  0  0  0  0  0 15]
 [ 0 23  0  0  0  0  0  0  0  9 38]
 [ 1  0 44  0  0  0  1  0  0  0 24]
 [ 0  0  5 47  0  0  0  0  0  0 18]
 [ 0  0  4  0 29  0  0  0  0  0 37]
 [ 2  0  4  0  0 54  2  1  0  0  7]
 [ 0  0  4  0  0  0 45  0  0  0 21]
 [ 0  0  0  0  0  0  0 58  0  0 12]
 [ 1  0  1  0  0  0  0  0 45  0 23]
 [ 0  0  1  0  0  0  0  0  0 54 15]
 [ 0  0  0  0  0  0  0  0  0  0  0]]

Metrics:
Accuracy: 0.6400
Precision: 0.9340
Recall: 0.6400
F1 Score: 0.7441


c:\Users\Azra\.vscode\venv\project\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
